import type { Metadata } from "next";
import { Corben, Manrope } from "next/font/google";
import "./globals.css";
import { SITE_NAME } from "@/lib/constant";
import { Header } from "@/components/header/Header";
import { Footer } from "@/components/footer/Footer";

const corben = Corben({
  variable: "--font-corben",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: `Home - ${SITE_NAME}`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${corben.variable} antialiased overflow-y-scroll`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
